name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: 7.1
            symfony-version: 3.4.*
          - php-version: 7.4
            symfony-version: 3.4.*
          - php-version: 7.1
            symfony-version: 4.4.*
          - php-version: 7.4
            symfony-version: 4.4.*
          - php-version: 7.2
            symfony-version: 5.0.*
          - php-version: 7.4
            symfony-version: 5.0.*

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.0.0

      - name: "Install dependencies with composer"
        run: |
          composer require --no-update --dev symfony/symfony:${{ matrix.symfony-version }}
          composer update --no-interaction --no-progress --no-suggest

      - name: "Run tests with phpunit/phpunit"
        run: vendor/bin/phpunit
