name: "Tests"

on:
  pull_request:
  push:
    branches:
      - "1.5"
      - "1.x"
      - "2.x"
      - "3.x"
      - "4.x"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: 8.1
            symfony-version: 6.4.*
          - php-version: 8.5
            symfony-version: 6.4.*

          - php-version: 8.2
            symfony-version: 7.4.*
          - php-version: 8.5
            symfony-version: 7.4.*

          - php-version: 8.4
            symfony-version: 8.0.*
          - php-version: 8.5
            symfony-version: 8.0.*

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: "symfony/flex is required to install the correct symfony version"
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require symfony/flex

      - name: "Configure Symfony version for symfony/flex"
        run: composer config extra.symfony.require "${{ matrix.symfony-version }}"

      - name: "Install dependencies with composer"
        run: composer update --no-interaction --no-progress

      - name: "Run tests with phpunit/phpunit"
        run: vendor/bin/phpunit

  codecov:
    name: "Code coverage"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: 8.5
            symfony-version: 8.0.*

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          php-version: ${{ matrix.php-version }}

      - name: "symfony/flex is required to install the correct symfony version"
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require symfony/flex

      - name: "Configure Symfony version for symfony/flex"
        run: composer config extra.symfony.require "${{ matrix.symfony-version }}"

      - name: "Install dependencies with composer"
        run: composer update --no-interaction --no-progress

      - name: "Run tests with phpunit/phpunit"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          vendor/bin/phpunit --coverage-clover coverage.xml

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1

  phpstan:
    name: "PhpStan"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: 8.5
            symfony-version: 8.0.*

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: "symfony/flex is required to install the correct symfony version"
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require symfony/flex

      - name: "Configure Symfony version for symfony/flex"
        run: composer config extra.symfony.require "${{ matrix.symfony-version }}"

      - name: "Install dependencies with composer"
        run: composer update --no-interaction --no-progress

      - name: "Run static analysis with phpstan/phpstan"
        run: vendor/bin/phpstan analyze

  checkstyle:
    name: "Checkstyle"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: 8.5
            symfony-version: 8.0.*

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: "symfony/flex is required to install the correct symfony version"
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require symfony/flex

      - name: "Configure Symfony version for symfony/flex"
        run: composer config extra.symfony.require "${{ matrix.symfony-version }}"

      - name: "Install dependencies with composer"
        run: composer update --no-interaction --no-progress

      - name: "Run checkstyle with squizlabs/php_codesniffer"
        run: vendor/bin/phpcs
